services:
  postgres:
    env_file:
      - .env
    container_name: postgres-wanderwise
    build:
      context: . 
      dockerfile: Dockerfile.pg
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5454:5432"
    restart: unless-stopped
    volumes:
      - postgres-wanderwise-data:/var/lib/postgresql/data
      - ./scripts/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - wanderwise-net

# Define the named volume
volumes:
  postgres-wanderwise-data:

# Define the network
networks:
  wanderwise-net: