# observability/prometheus.yml
global:
  scrape_interval: 15s # How often to scrape targets

scrape_configs:
  # Scrape metrics from your Go application's /metrics endpoint
  # - job_name: "wanderwise-api"
  #   static_configs:
  #     - targets: ["wanderwise-api:9090"] # Service name and port defined in docker-compose
  - job_name: "wanderwise-api"
    static_configs:
      # Use host.docker.internal and the port exposed by Go app on the host
      - targets: ["host.docker.internal:9090"] # <<< CHANGE HERE


  # Scrape metrics from the OTel Collector itself (optional)
  # - job_name: 'otel-collector'
  #   static_configs:
  #     - targets: ['otel-collector:8888']

  # Scrape Prometheus itself (optional)
  # - job_name: 'prometheus'
  #   static_configs:
  #     - targets: ['localhost:9090'] # Prometheus runs on 9090 inside its container
