apiVersion: v1
kind: Secret
metadata:
  name: {{ include "loci-server.fullname" . }}-secrets
  labels:
    {{- include "loci-server.labels" . | nindent 4 }}
type: Opaque
data:
  database-password: {{ .Values.secrets.database.password | b64enc | quote }}
  jwt-secret: {{ .Values.secrets.jwt.secret | b64enc | quote }}
  openai-api-key: {{ .Values.secrets.openai.apiKey | b64enc | quote }}