name: Branch Protection Setup

on:
  workflow_dispatch:

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    steps:
    - name: Setup branch protection for main
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          
          // Main branch protection
          await github.rest.repos.updateBranchProtection({
            owner,
            repo,
            branch: 'main',
            required_status_checks: {
              strict: true,
              contexts: ['test', 'lint', 'build']
            },
            enforce_admins: false,
            required_pull_request_reviews: {
              required_approving_review_count: 1,
              dismiss_stale_reviews: true,
              require_code_owner_reviews: false,
              require_last_push_approval: false
            },
            restrictions: null,
            allow_force_pushes: false,
            allow_deletions: false,
            block_creations: false,
            required_conversation_resolution: true
          });
          
          console.log('Branch protection rules set for main branch');

    - name: Setup branch protection for dev
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          
          // Dev branch protection (lighter restrictions)
          await github.rest.repos.updateBranchProtection({
            owner,
            repo,
            branch: 'dev',
            required_status_checks: {
              strict: true,
              contexts: ['test', 'lint', 'build']
            },
            enforce_admins: false,
            required_pull_request_reviews: null,
            restrictions: null,
            allow_force_pushes: false,
            allow_deletions: false,
            block_creations: false,
            required_conversation_resolution: false
          });
          
          console.log('Branch protection rules set for dev branch');